# Generated by Django 4.1.7 on 2023-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Surname', models.CharField(max_length=64)),
                ('CreationDate', models.DateTimeField()),
                ('type_user', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
