# Generated by Django 4.1.7 on 2023-04-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Avapp', '0002_appuser_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abundancefacttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abundance', models.CharField(blank=True, db_column='Abundance', max_length=45, null=True)),
            ],
            options={
                'db_table': 'AbundanceFactTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('idanalysis', models.AutoField(db_column='IdAnalysis', primary_key=True, serialize=False)),
                ('analysisname', models.CharField(blank=True, db_column='AnalysisName', max_length=45, null=True)),
                ('parameter', models.CharField(blank=True, db_column='Parameter', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'Analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvappAppuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=64)),
                ('surname', models.CharField(db_column='Surname', max_length=64)),
                ('creationdate', models.DateTimeField(db_column='CreationDate')),
                ('type_user', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Avapp_appuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('idfeature', models.AutoField(db_column='IdFeature', primary_key=True, serialize=False)),
                ('featurename', models.CharField(blank=True, db_column='FeatureName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Feature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('idgene', models.AutoField(db_column='IdGene', primary_key=True, serialize=False)),
                ('genename', models.CharField(blank=True, db_column='GeneName', max_length=45, null=True)),
                ('length', models.IntegerField(blank=True, db_column='Length', null=True)),
            ],
            options={
                'db_table': 'Gene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('idgenome', models.AutoField(db_column='IdGenome', primary_key=True, serialize=False)),
                ('genomecategory', models.CharField(blank=True, db_column='GenomeCategory', max_length=45, null=True)),
                ('domain', models.CharField(blank=True, db_column='Domain', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Genome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('idhost', models.AutoField(db_column='IdHost', primary_key=True, serialize=False)),
                ('tag', models.IntegerField(blank=True, db_column='Tag', null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=45, null=True)),
                ('growthroom', models.CharField(blank=True, db_column='GrowthRoom', max_length=45, null=True)),
                ('weight', models.TextField(blank=True, db_column='Weight', null=True)),
            ],
            options={
                'db_table': 'Host',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostHasPen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Host_has_Pen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('iditem', models.AutoField(db_column='IdItem', primary_key=True, serialize=False)),
                ('itemname', models.CharField(db_column='ItemName', max_length=45)),
            ],
            options={
                'db_table': 'Item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Omics',
            fields=[
                ('idomics', models.AutoField(db_column='IdOmics', primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, db_column='Path', max_length=250, null=True)),
                ('technology', models.CharField(blank=True, db_column='Technology', max_length=45, null=True)),
                ('platform', models.CharField(blank=True, db_column='Platform', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Omics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('idpen', models.AutoField(db_column='IdPen', primary_key=True, serialize=False)),
                ('trt', models.IntegerField(blank=True, db_column='Trt', null=True)),
                ('donorhen', models.CharField(blank=True, db_column='DonorHen', max_length=45, null=True)),
                ('dietstarter', models.CharField(blank=True, db_column='DietStarter', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Pen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PenHasFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, db_column='Value', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Pen_has_Feature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('idquality', models.AutoField(db_column='IdQuality', primary_key=True, serialize=False)),
                ('qualityname', models.CharField(blank=True, db_column='QualityName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Quality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('idsample', models.AutoField(db_column='IdSample', primary_key=True, serialize=False)),
                ('collectiondate', models.DateField(blank=True, db_column='CollectionDate', null=True)),
                ('samplename', models.CharField(blank=True, db_column='SampleName', max_length=45, null=True)),
                ('sampletype', models.CharField(blank=True, db_column='SampleType', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Sample',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('idset', models.AutoField(db_column='IdSet', primary_key=True, serialize=False)),
                ('settype', models.CharField(blank=True, db_column='SetType', max_length=45, null=True)),
                ('setname', models.CharField(blank=True, db_column='SetName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetHasGenome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infos', models.CharField(blank=True, db_column='Infos', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'Set_has_Genome',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('idstudy', models.AutoField(db_column='idStudy', primary_key=True, serialize=False)),
                ('studyname', models.CharField(blank=True, db_column='StudyName', max_length=45, null=True, unique=True)),
                ('studydate', models.DateField(blank=True, db_column='StudyDate', null=True)),
                ('summary', models.TextField(blank=True, db_column='Summary', null=True)),
            ],
            options={
                'db_table': 'Study',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxons',
            fields=[
                ('idtaxons', models.AutoField(db_column='IdTaxons', primary_key=True, serialize=False)),
                ('taxonomy', models.CharField(blank=True, db_column='Taxonomy', max_length=2000, null=True)),
                ('size', models.IntegerField(blank=True, db_column='Size', null=True)),
            ],
            options={
                'db_table': 'Taxons',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='appuser',
            name='type_user',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Featurefacttable',
            fields=[
                ('host_idhost', models.OneToOneField(db_column='Host_idHost', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Avapp.host')),
                ('value', models.CharField(blank=True, db_column='Value', max_length=45, null=True)),
            ],
            options={
                'db_table': 'FeatureFactTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OmicsHasQuality',
            fields=[
                ('omics_idomics', models.OneToOneField(db_column='Omics_idOmics', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Avapp.omics')),
                ('values', models.CharField(blank=True, db_column='Values', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Omics_has_Quality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SetHasGene',
            fields=[
                ('gene_idgene', models.OneToOneField(db_column='Gene_IdGene', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Avapp.gene')),
                ('info', models.CharField(blank=True, db_column='Info', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'Set_has_Gene',
                'managed': False,
            },
        ),
    ]
