# Generated by Django 3.2.18 on 2025-04-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avapp', '0003_abundancefacttable_analysis_authgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TissueCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_tissue', models.CharField(max_length=50)),
                ('to_tissue', models.CharField(max_length=50)),
                ('var1', models.CharField(max_length=200)),
                ('var2', models.CharField(max_length=200)),
                ('correlation', models.FloatField(blank=True, null=True)),
                ('pvalue', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('min_val', models.FloatField(blank=True, null=True)),
                ('max_val', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'avapp_tissuecorrelation',
            },
        ),
        migrations.AddIndex(
            model_name='tissuecorrelation',
            index=models.Index(fields=['var1', 'var2'], name='avapp_tissu_var1_ed6735_idx'),
        ),
    ]
