# Generated by Django 3.2.18 on 2025-04-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avapp', '0004_auto_20250403_1447'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tissuecorrelation',
            name='avapp_tissu_var1_ed6735_idx',
        ),
        migrations.RenameField(
            model_name='tissuecorrelation',
            old_name='max_val',
            new_name='max',
        ),
        migrations.RenameField(
            model_name='tissuecorrelation',
            old_name='min_val',
            new_name='min',
        ),
        migrations.AddIndex(
            model_name='tissuecorrelation',
            index=models.Index(fields=['var1', 'var2'], name='Avapp_tissu_var1_1a22b7_idx'),
        ),
        migrations.AlterModelTable(
            name='tissuecorrelation',
            table=None,
        ),
    ]
