# Generated by Django 3.2.18 on 2025-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avapp', '0005_auto_20250403_1521'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tissuecorrelation',
            index=models.Index(condition=models.Q(('from_tissue', 'ileum'), ('to_tissue', 'ileum')), fields=['accuracy', '-correlation'], include=('var1', 'var2', 'min', 'max', 'pvalue'), name='idx_tc_ileum_explore_all'),
        ),
    ]
