# Generated by Django 3.2.18 on 2025-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avapp', '0006_tissuecorrelation_idx_tc_ileum_explore_all'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tissuecorrelation',
            name='Avapp_tissu_var1_1a22b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='tissuecorrelation',
            name='idx_tc_ileum_explore_all',
        ),
        migrations.AddIndex(
            model_name='tissuecorrelation',
            index=models.Index(fields=['from_tissue', 'to_tissue', 'correlation', 'accuracy'], name='Avapp_tissu_from_ti_71e98b_idx'),
        ),
        migrations.AddIndex(
            model_name='tissuecorrelation',
            index=models.Index(condition=models.Q(('from_tissue', 'ileum'), ('to_tissue', 'ileum')), fields=['correlation', 'accuracy'], name='ileum_idx'),
        ),
    ]
