-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."AbundanceFactTable"
(
    "Sample_idSample" integer NOT NULL,
    "Item_idItem" integer NOT NULL,
    "Omics_idOMICS" integer NOT NULL,
    "Abundances" character varying(45) COLLATE pg_catalog."default",
    id serial NOT NULL,
    "Abundance" numeric,
    CONSTRAINT "AbundanceFactTable_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."AbundanceFactTable_M2D2"
(
    "Sample_idSample_M2D2" integer NOT NULL,
    "Item_idItem" integer NOT NULL,
    "Omics_idOmics" integer NOT NULL,
    id integer NOT NULL,
    "Abundance" numeric NOT NULL,
    CONSTRAINT "AbundanceFactTable_M2D2_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Analysis"
(
    "IdAnalysis" serial NOT NULL,
    "AnalysisName" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    "Set_IdSet" integer,
    "Parameter" character varying(2000) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    CONSTRAINT "Analysis_pkey" PRIMARY KEY ("IdAnalysis")
);

CREATE TABLE IF NOT EXISTS public."Avapp_appuser"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Name" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "Surname" character varying(64) COLLATE pg_catalog."default" NOT NULL,
    "CreationDate" timestamp with time zone NOT NULL,
    type_user character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Avapp_appuser_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."CompoundInformation"
(
    "IdCompoundInformation" integer NOT NULL DEFAULT nextval('"Feature_IdFeature_seq"'::regclass),
    "CompoundName" character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT "CompoundInformation_pkey" PRIMARY KEY ("IdCompoundInformation")
);

CREATE TABLE IF NOT EXISTS public."Feature"
(
    "IdFeature" serial NOT NULL,
    "FeatureName" character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT "unique_IdFeature" PRIMARY KEY ("IdFeature")
);

CREATE TABLE IF NOT EXISTS public."FeatureFactTable"
(
    "Host_idHost" integer NOT NULL,
    "Feature_idFeature" integer NOT NULL,
    "Value" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL '::character varying,
    CONSTRAINT "FeatureFactTable_pkey" PRIMARY KEY ("Host_idHost", "Feature_idFeature")
);

CREATE TABLE IF NOT EXISTS public."Feature_M2D2"
(
    "Id_Feature" integer NOT NULL,
    "FeatureName" character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT "Feature_M2D2_pkey" PRIMARY KEY ("Id_Feature")
);

CREATE TABLE IF NOT EXISTS public."Gene"
(
    "IdGene" serial NOT NULL,
    "GeneName" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    "Length" integer DEFAULT 0,
    "Genome_idGenome" integer NOT NULL,
    CONSTRAINT "pk_IdGene" PRIMARY KEY ("IdGene")
);

CREATE TABLE IF NOT EXISTS public."Genome"
(
    "IdGenome" serial NOT NULL,
    "GenomeCategory" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    "Domain" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    CONSTRAINT "Genome_pkey" PRIMARY KEY ("IdGenome")
);

CREATE TABLE IF NOT EXISTS public."Host"
(
    "IdHost" serial NOT NULL,
    "Tag" integer DEFAULT 0,
    "Sex" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    "GrowthRoom" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    "Study_idStudy" integer NOT NULL,
    "Weight" jsonb DEFAULT '{}'::json,
    CONSTRAINT "idHost_UNIQUE" PRIMARY KEY ("IdHost")
);

CREATE TABLE IF NOT EXISTS public."Host_has_Pen"
(
    "Pen_IdPen" serial NOT NULL,
    "Host_IdHost" integer NOT NULL,
    id serial NOT NULL,
    CONSTRAINT "Host_has_Pen_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Item"
(
    "IdItem" serial NOT NULL,
    "ItemName" character varying(45) COLLATE pg_catalog."default" NOT NULL,
    "Analysis_IdAnalysis" integer NOT NULL,
    CONSTRAINT "Item_pkey" PRIMARY KEY ("IdItem"),
    CONSTRAINT "Unique_ItemName_Analysis_IdAnalysis" UNIQUE ("ItemName", "Analysis_IdAnalysis")
);

CREATE TABLE IF NOT EXISTS public."Item_has_CompoundInformation"
(
    "CompoundInformation_IdCompoundInformartion" integer NOT NULL,
    "Item_IdItem" integer NOT NULL,
    "Value" character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT pk_item_compound PRIMARY KEY ("CompoundInformation_IdCompoundInformartion", "Item_IdItem")
);

CREATE TABLE IF NOT EXISTS public."Omics"
(
    "IdOmics" serial NOT NULL,
    "Path" character varying(250) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    "Technology" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    "Platform" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    CONSTRAINT "idOmics_UNIQUE" PRIMARY KEY ("IdOmics")
);

CREATE TABLE IF NOT EXISTS public."Omics_has_Quality"
(
    "Omics_idOmics" integer NOT NULL,
    "Quality_idQuality" integer NOT NULL,
    "Values" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    CONSTRAINT "Omics_has_Quality_pkey" PRIMARY KEY ("Omics_idOmics", "Quality_idQuality")
);

CREATE TABLE IF NOT EXISTS public."Pen"
(
    "IdPen" serial NOT NULL,
    "Trt" integer,
    "DonorHen" character varying(45) COLLATE pg_catalog."default",
    "DietStarter" character varying(45) COLLATE pg_catalog."default",
    "PenIdentifier" integer,
    "Treatment" character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT "Pen_pkey" PRIMARY KEY ("IdPen")
);

CREATE TABLE IF NOT EXISTS public."Pen_has_Feature"
(
    "Feature_IdFeature" integer NOT NULL,
    "Pen_IdPen" serial NOT NULL,
    "Value" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    id serial NOT NULL,
    CONSTRAINT "Pen_has_Feature_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Quality"
(
    "IdQuality" serial NOT NULL,
    "QualityName" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    CONSTRAINT "idQuality_UNIQUE" PRIMARY KEY ("IdQuality")
);

CREATE TABLE IF NOT EXISTS public."Sample"
(
    "IdSample" serial NOT NULL,
    "CollectionDate" date,
    "SampleName" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    "Host_idHost" integer NOT NULL,
    "SampleType" character varying(45) COLLATE pg_catalog."default",
    "Weight" numeric,
    "Infos" character varying(380) COLLATE pg_catalog."default",
    CONSTRAINT "idSample_UNIQUE" PRIMARY KEY ("IdSample")
);

CREATE TABLE IF NOT EXISTS public."Sample_M2D2"
(
    "Id_Sample" integer NOT NULL,
    "Sequencing_ID" character varying(45) COLLATE pg_catalog."default",
    "Sample_ID" character varying(45) COLLATE pg_catalog."default",
    "Notes" character varying(245) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    "Plate_Location" character varying(45) COLLATE pg_catalog."default",
    "Sample_type" character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT "Sample_M2D2_pkey" PRIMARY KEY ("Id_Sample")
);

CREATE TABLE IF NOT EXISTS public."Sample_M2D2_has_Feature"
(
    "Sample_idSample_M2D2" integer NOT NULL,
    "Feature_idFeature_M2D2" integer NOT NULL,
    "Value" character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT "Sample_M2D2_has_Feature_pkey" PRIMARY KEY ("Sample_idSample_M2D2", "Feature_idFeature_M2D2")
);

CREATE TABLE IF NOT EXISTS public."Set"
(
    "IdSet" serial NOT NULL,
    "SetType" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    "SetName" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    CONSTRAINT "Set_pkey" PRIMARY KEY ("IdSet")
);

CREATE TABLE IF NOT EXISTS public."Set_has_Gene"
(
    "Gene_IdGene" integer NOT NULL,
    "Set_IdSet" integer NOT NULL,
    "Info" character varying(2000) COLLATE pg_catalog."default",
    CONSTRAINT "pk_Set_has_Gene" PRIMARY KEY ("Gene_IdGene", "Set_IdSet")
);

CREATE TABLE IF NOT EXISTS public."Set_has_Genome"
(
    "Set_IdSet" integer,
    "Genome_IdGenome" integer,
    "Infos" character varying(2000) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public."Study"
(
    "idStudy" serial NOT NULL,
    "StudyName" character varying(45) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    "StudyDate" date DEFAULT CURRENT_DATE,
    "Summary" text COLLATE pg_catalog."default",
    CONSTRAINT "idStudy_UNIQUE" PRIMARY KEY ("idStudy"),
    CONSTRAINT "Unique_StudyName" UNIQUE ("StudyName")
);

CREATE TABLE IF NOT EXISTS public."Taxons"
(
    "IdTaxons" integer NOT NULL DEFAULT nextval('"Taxons_new_IdTaxons_seq"'::regclass),
    "Item_idItem" integer NOT NULL,
    "Taxonomy" character varying(2000) COLLATE pg_catalog."default" DEFAULT 'NULL'::character varying,
    "Size" integer,
    CONSTRAINT "Taxons_pkey_1" PRIMARY KEY ("IdTaxons")
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.authtoken_token
(
    key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT authtoken_token_pkey PRIMARY KEY (key),
    CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.avapp_tissuecorrelation
(
    id serial NOT NULL,
    from_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    to_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    var1 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    var2 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    correlation double precision,
    pvalue double precision,
    accuracy double precision,
    min double precision,
    max double precision,
    CONSTRAINT avapp_tissuecorrelation_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.avapp_tissuecorrelation_acid
(
    id serial NOT NULL,
    from_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    to_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    var1 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    var2 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    correlation double precision,
    pvalue double precision,
    accuracy double precision,
    min double precision,
    max double precision,
    CONSTRAINT avapp_tissuecorrelation_acid_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.avapp_tissuecorrelation_functionnal
(
    id serial NOT NULL,
    from_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    to_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    var1 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    var2 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    correlation double precision,
    pvalue double precision,
    accuracy double precision,
    min double precision,
    max double precision,
    CONSTRAINT avapp_tissuecorrelation_functionnal_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.avapp_tissuecorrelation_liver
(
    id serial NOT NULL,
    from_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    to_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    var1 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    var2 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    correlation double precision,
    pvalue double precision,
    accuracy double precision,
    min double precision,
    max double precision,
    CONSTRAINT avapp_tissuecorrelation_liver_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.avapp_tissuecorrelation_metab
(
    id serial NOT NULL,
    from_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    to_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    var1 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    var2 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    correlation double precision,
    pvalue double precision,
    accuracy double precision,
    min double precision,
    max double precision,
    CONSTRAINT avapp_tissuecorrelation_metab_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.avapp_tissuecorrelation_muscle
(
    id serial NOT NULL,
    from_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    to_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    var1 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    var2 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    correlation double precision,
    pvalue double precision,
    accuracy double precision,
    min double precision,
    max double precision,
    CONSTRAINT avapp_tissuecorrelation_muscle_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.avapp_tissuecorrelation_muscle_ross
(
    id serial NOT NULL,
    from_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    to_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    var1 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    var2 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    correlation double precision,
    pvalue double precision,
    accuracy double precision,
    min double precision,
    max double precision,
    CONSTRAINT avapp_tissuecorrelation_muscle_ross_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.avapp_tissuecorrelation_otu
(
    id serial NOT NULL,
    from_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    to_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    var1 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    var2 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    correlation double precision,
    pvalue double precision,
    accuracy double precision,
    min double precision,
    max double precision,
    CONSTRAINT avapp_tissuecorrelation_otu_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.avapp_tissuecorrelation_otu_ross
(
    id serial NOT NULL,
    from_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    to_tissue character varying(50) COLLATE pg_catalog."default" NOT NULL,
    var1 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    var2 character varying(200) COLLATE pg_catalog."default" NOT NULL,
    correlation double precision,
    pvalue double precision,
    accuracy double precision,
    min double precision,
    max double precision,
    CONSTRAINT avapp_tissuecorrelation_otu_ross_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_clockedschedule
(
    id serial NOT NULL,
    clocked_time timestamp with time zone NOT NULL,
    CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_crontabschedule
(
    id serial NOT NULL,
    minute character varying(240) COLLATE pg_catalog."default" NOT NULL,
    hour character varying(96) COLLATE pg_catalog."default" NOT NULL,
    day_of_week character varying(64) COLLATE pg_catalog."default" NOT NULL,
    day_of_month character varying(124) COLLATE pg_catalog."default" NOT NULL,
    month_of_year character varying(64) COLLATE pg_catalog."default" NOT NULL,
    timezone character varying(63) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_intervalschedule
(
    id serial NOT NULL,
    every integer NOT NULL,
    period character varying(24) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_periodictask
(
    id serial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    task character varying(200) COLLATE pg_catalog."default" NOT NULL,
    args text COLLATE pg_catalog."default" NOT NULL,
    kwargs text COLLATE pg_catalog."default" NOT NULL,
    queue character varying(200) COLLATE pg_catalog."default",
    exchange character varying(200) COLLATE pg_catalog."default",
    routing_key character varying(200) COLLATE pg_catalog."default",
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text COLLATE pg_catalog."default" NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id),
    CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_periodictasks
(
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL,
    CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_solarschedule
(
    id serial NOT NULL,
    event character varying(24) COLLATE pg_catalog."default" NOT NULL,
    latitude numeric(9, 6) NOT NULL,
    longitude numeric(9, 6) NOT NULL,
    CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id),
    CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude)
);

CREATE TABLE IF NOT EXISTS public.django_celery_results_chordcounter
(
    id serial NOT NULL,
    group_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    sub_tasks text COLLATE pg_catalog."default" NOT NULL,
    count integer NOT NULL,
    CONSTRAINT django_celery_results_chordcounter_pkey PRIMARY KEY (id),
    CONSTRAINT django_celery_results_chordcounter_group_id_key UNIQUE (group_id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_results_groupresult
(
    id serial NOT NULL,
    group_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_done timestamp with time zone NOT NULL,
    content_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    content_encoding character varying(64) COLLATE pg_catalog."default" NOT NULL,
    result text COLLATE pg_catalog."default",
    CONSTRAINT django_celery_results_groupresult_pkey PRIMARY KEY (id),
    CONSTRAINT django_celery_results_groupresult_group_id_key UNIQUE (group_id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_results_taskresult
(
    id serial NOT NULL,
    task_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    content_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    content_encoding character varying(64) COLLATE pg_catalog."default" NOT NULL,
    result text COLLATE pg_catalog."default",
    date_done timestamp with time zone NOT NULL,
    traceback text COLLATE pg_catalog."default",
    meta text COLLATE pg_catalog."default",
    task_args text COLLATE pg_catalog."default",
    task_kwargs text COLLATE pg_catalog."default",
    task_name character varying(255) COLLATE pg_catalog."default",
    worker character varying(100) COLLATE pg_catalog."default",
    date_created timestamp with time zone NOT NULL,
    periodic_task_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT django_celery_results_taskresult_pkey PRIMARY KEY (id),
    CONSTRAINT django_celery_results_taskresult_task_id_key UNIQUE (task_id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_plotly_dash_dashapp
(
    id bigserial NOT NULL,
    instance_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(110) COLLATE pg_catalog."default" NOT NULL,
    base_state text COLLATE pg_catalog."default" NOT NULL,
    creation timestamp with time zone NOT NULL,
    update timestamp with time zone NOT NULL,
    save_on_change boolean NOT NULL,
    stateless_app_id bigint NOT NULL,
    CONSTRAINT django_plotly_dash_dashapp_pkey PRIMARY KEY (id),
    CONSTRAINT django_plotly_dash_dashapp_instance_name_key UNIQUE (instance_name),
    CONSTRAINT django_plotly_dash_dashapp_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.django_plotly_dash_statelessapp
(
    id bigserial NOT NULL,
    app_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(110) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_plotly_dash_statelessapp_pkey PRIMARY KEY (id),
    CONSTRAINT django_plotly_dash_statelessapp_app_name_key UNIQUE (app_name),
    CONSTRAINT django_plotly_dash_statelessapp_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

ALTER TABLE IF EXISTS public."AbundanceFactTable"
    ADD CONSTRAINT "fk_AbundanceFactTable_Item_idx" FOREIGN KEY ("Item_idItem")
    REFERENCES public."Item" ("IdItem") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."AbundanceFactTable"
    ADD CONSTRAINT "fk_AbundanceFactTable_Omics_idx" FOREIGN KEY ("Omics_idOMICS")
    REFERENCES public."Omics" ("IdOmics") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."AbundanceFactTable"
    ADD CONSTRAINT "fk_AbundanceFactTable_Sample_idx" FOREIGN KEY ("Sample_idSample")
    REFERENCES public."Sample" ("IdSample") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."AbundanceFactTable_M2D2"
    ADD CONSTRAINT "fk_AbundanceFactTable_Item_idx" FOREIGN KEY ("Item_idItem")
    REFERENCES public."Item" ("IdItem") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."AbundanceFactTable_M2D2"
    ADD CONSTRAINT "fk_AbundanceFactTable_Omics_idx" FOREIGN KEY ("Omics_idOmics")
    REFERENCES public."Omics" ("IdOmics") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."AbundanceFactTable_M2D2"
    ADD CONSTRAINT "fk_AbundanceFactTable_Sample_M2D2D_idx" FOREIGN KEY ("Sample_idSample_M2D2")
    REFERENCES public."Sample_M2D2" ("Id_Sample") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Analysis"
    ADD CONSTRAINT "fk_Set_IdSet" FOREIGN KEY ("Set_IdSet")
    REFERENCES public."Set" ("IdSet") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FeatureFactTable"
    ADD CONSTRAINT "fk-idFeature" FOREIGN KEY ("Feature_idFeature")
    REFERENCES public."Feature" ("IdFeature") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FeatureFactTable"
    ADD CONSTRAINT "fk_idHost" FOREIGN KEY ("Host_idHost")
    REFERENCES public."Host" ("IdHost") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Gene"
    ADD CONSTRAINT "fk_Gene_IdGenome" FOREIGN KEY ("Genome_idGenome")
    REFERENCES public."Genome" ("IdGenome") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Host"
    ADD CONSTRAINT "fk_Host_Study" FOREIGN KEY ("Study_idStudy")
    REFERENCES public."Study" ("idStudy") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Host_has_Pen"
    ADD CONSTRAINT "Host_has_Pen_Host_IdHost_fkey" FOREIGN KEY ("Host_IdHost")
    REFERENCES public."Host" ("IdHost") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Host_has_Pen"
    ADD CONSTRAINT "Host_has_Pen_Pen_IdPen_fkey" FOREIGN KEY ("Pen_IdPen")
    REFERENCES public."Pen" ("IdPen") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Item"
    ADD CONSTRAINT "fk_Analysis_IdAnalysis" FOREIGN KEY ("Analysis_IdAnalysis")
    REFERENCES public."Analysis" ("IdAnalysis") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Item_has_CompoundInformation"
    ADD CONSTRAINT "FK_compoundInformation" FOREIGN KEY ("CompoundInformation_IdCompoundInformartion")
    REFERENCES public."CompoundInformation" ("IdCompoundInformation") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Item_has_CompoundInformation"
    ADD CONSTRAINT "FK_idItem" FOREIGN KEY ("Item_IdItem")
    REFERENCES public."Item" ("IdItem") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Omics_has_Quality"
    ADD CONSTRAINT "fk_Omics_has_Quality_Omics" FOREIGN KEY ("Omics_idOmics")
    REFERENCES public."Omics" ("IdOmics") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Omics_has_Quality"
    ADD CONSTRAINT "fk_Omics_has_Quality_Quality" FOREIGN KEY ("Quality_idQuality")
    REFERENCES public."Quality" ("IdQuality") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pen_has_Feature"
    ADD CONSTRAINT "Pen_has_Feature_Feature_IdFeature_fkey" FOREIGN KEY ("Feature_IdFeature")
    REFERENCES public."Feature" ("IdFeature") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pen_has_Feature"
    ADD CONSTRAINT "Pen_has_Feature_Pen_IdPen_fkey" FOREIGN KEY ("Pen_IdPen")
    REFERENCES public."Pen" ("IdPen") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sample"
    ADD CONSTRAINT "fk_Sample_Host" FOREIGN KEY ("Host_idHost")
    REFERENCES public."Host" ("IdHost") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sample_M2D2_has_Feature"
    ADD CONSTRAINT "FK_Features_M2D2" FOREIGN KEY ("Feature_idFeature_M2D2")
    REFERENCES public."Feature_M2D2" ("Id_Feature") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Sample_M2D2_has_Feature"
    ADD CONSTRAINT "FK_Sample_M2D2" FOREIGN KEY ("Sample_idSample_M2D2")
    REFERENCES public."Sample_M2D2" ("Id_Sample") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Set_has_Gene"
    ADD CONSTRAINT "fk_Gene_IdGene" FOREIGN KEY ("Gene_IdGene")
    REFERENCES public."Gene" ("IdGene") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Set_has_Gene"
    ADD CONSTRAINT "fk_Set_IdSet" FOREIGN KEY ("Set_IdSet")
    REFERENCES public."Set" ("IdSet") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Set_has_Genome"
    ADD CONSTRAINT "fk_Set_has_Genome_IdGenome" FOREIGN KEY ("Genome_IdGenome")
    REFERENCES public."Genome" ("IdGenome") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Set_has_Genome"
    ADD CONSTRAINT "fk_Set_has_Genome_IdSet" FOREIGN KEY ("Set_IdSet")
    REFERENCES public."Set" ("IdSet") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Taxons"
    ADD CONSTRAINT fk_taxon FOREIGN KEY ("Item_idItem")
    REFERENCES public."Item" ("IdItem") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS authtoken_token_user_id_key
    ON public.authtoken_token(user_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id)
    REFERENCES public.django_celery_beat_clockedschedule (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_celery_beat_periodictask_clocked_id_47a69f82
    ON public.django_celery_beat_periodictask(clocked_id);


ALTER TABLE IF EXISTS public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id)
    REFERENCES public.django_celery_beat_crontabschedule (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_celery_beat_periodictask_crontab_id_d3cba168
    ON public.django_celery_beat_periodictask(crontab_id);


ALTER TABLE IF EXISTS public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id)
    REFERENCES public.django_celery_beat_intervalschedule (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_celery_beat_periodictask_interval_id_a8ca27da
    ON public.django_celery_beat_periodictask(interval_id);


ALTER TABLE IF EXISTS public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id)
    REFERENCES public.django_celery_beat_solarschedule (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_celery_beat_periodictask_solar_id_a87ce72c
    ON public.django_celery_beat_periodictask(solar_id);


ALTER TABLE IF EXISTS public.django_plotly_dash_dashapp
    ADD CONSTRAINT django_plotly_dash_dashapp_stateless_app_id_220444de_fk FOREIGN KEY (stateless_app_id)
    REFERENCES public.django_plotly_dash_statelessapp (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_plotly_dash_dashapp_stateless_app_id_220444de
    ON public.django_plotly_dash_dashapp(stateless_app_id);

END;
